### ISSUE TITLE
ImportError re PIL

### ISSUE THREAD

**Issue by CasonUK** [rounakbanik/generative-art-nft#16]
When I run nft.py I get the following error message:

File "nft.py", line 5, in <module>
    from PIL import Image
ImportError: No module named PIL

I've tried uninstalling pil and pillow and reinstalling pillow, but the error keeps arising. Any thoughts??

Thanks!

**Comment by cloud10labs** [comment]
any update on this?

**Comment by rounakbanik** [comment]
Use `pip3` instead of `pip` and `python3` instead of `python`

**Comment by CasonUK** [comment]
Thanks! Worked like a charm.
