### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by mirza-sundus** [rounakbanik/generative-art-nft#17]
Checking assets...
Assets look great! We are good to go!

You can create a total of 16 distinct avatars

How many avatars would you like to create? Enter a number greater than 0: 
1
What would you like to call this edition?: 
edition3
Starting task...
Traceback (most recent call last):
  File "nft.py", line 238, in <module>
    main()
  File "nft.py", line 229, in main
    rt = generate_images(edition_name, num_avatars)
  File "nft.py", line 164, in generate_images
    for n in progressbar(range(count)):
TypeError: 'module' object is not callable

**Comment by rounakbanik** [comment]
Run `pip install progressbar2` and try again.
