### ISSUE TITLE
Progressbar doesn't works well.

### ISSUE THREAD

**Issue by thunderstroke325** [rounakbanik/generative-art-nft#20]
I installed the "progressbar" package but it occur issue.
after I remove the progressbar feature from the script, it works fine.

**Comment by levintech** [comment]
I fix the progressbar issue. 
There are many progressbar packages on python language. We should use correct one of them in this project.
I found correct one and attached the requirements packages below.

numpy==1.21.5
pandas==1.3.5
Pillow==9.0.1
progressbar2==4.0.0
python-dateutil==2.8.2
python-utils==3.1.0
pytz==2021.3
six==1.16.0

Hope to helpful to someone.
Best Regards.
