### ISSUE TITLE
Base Image URL for generating metadata

### ISSUE THREAD

**Issue by amitbakhru** [rounakbanik/generative-art-nft#5]
When generating metadata using the metadata.py, what should be used as the BASE_IMAGE_URL? I haven't uploaded my images on any website yet. I have generated multiple sets and those are still in my local storage. Can you please provide some guidance on how to use the metadata.py? Thanks.

**Comment by rounakbanik** [comment]
The BASE_IMAGE_URL should be set to the IPFS URL of the folder containing your images. We have detailed tutorial explaining how to work with metadata and IPFS. Check it out here: https://medium.com/scrappy-squirrels/tutorial-nft-metadata-ipfs-and-pinata-9ab1948669a3

**Comment by amitbakhru** [comment]
Hi Raunak,

First of all I would like to tell you how much I appreciate you posting these articles. This has helped us a long way in getting started with our NFT project. Kudos to you.

I did go through the article pointed out by you, but it expects that by following the earlier article about how to generate images, as an output we should already have a collection of PNG images (which we have) and a metadata CSV file as well. But when I run the nft.py program, it only generates the PNG images. I do not see any CSV file generated. Would you be able to help as to how the metadata CSV file will be generated? 

Again, thanks so much for your help with this.

Amit.

**Comment by amitbakhru** [comment]
Hi Raunak,

Sorry for bombing you with multiple emails. But I can see the metadata CSV file now. Again, really appreciate what you have done for the community!

Amit.
