### ISSUE TITLE
Error on Thumbs.db

### ISSUE THREAD

**Issue by crhall** [rounakbanik/generative-art-nft#7]
I have hidden files turned on and cannot see Thumbs.db, but the script throws errors for various folders and Thumbs.db.
Any clue how to get it to ignore it?

Starting task...
  0% (0 of 4200) |                                                               | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "nft.py", line 237, in <module>
    main()
  File "nft.py", line 228, in main
    rt = generate_images(edition_name, num_avatars)
  File "nft.py", line 172, in generate_images
    generate_single_image(trait_paths, os.path.join(op_path, image_name))
  File "nft.py", line 72, in generate_single_image
    img = Image.open(os.path.join('assets', filepath))
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'assets\\Body\\Thumbs.db'

**Comment by rounakbanik** [comment]
This issue has been fixed courtesy @biranchi2018
